### ISSUE TITLE
Idk how to fix that

### ISSUE THREAD

**Issue by Z95250** [wrrulos/MCPTool#26]
Traceback (most recent call last):
  File "C:\Users\HelloGithub\Desktop\MCP\MCPTool-main\main.py", line 2673, in <module>
    save_settings()
  File "C:\Users\HelloGithub\Desktop\MCP\MCPTool-main\main.py", line 367, in save_settings
    version_check = js['version_check']  # Decide if you want to check for a possible update when opening the script
KeyError: 'version_check'

**Comment by albymorf** [comment]
Same error

**Comment by wrrulos** [comment]
That's because it was updating the entire program. Download the new version!
