### ISSUE TITLE
says this error

### ISSUE THREAD

**Issue by vofq** [wrrulos/MCPTool#38]
Traceback (most recent call last):
  File "C:\Users\info\Downloads\MCPTool-3.5\MCPTool-3.5\main.py", line 7, in <module>
    from utils.checks.CommandArguments import check_command_arguments
  File "C:\Users\info\Downloads\MCPTool-3.5\MCPTool-3.5\utils\checks\CommandArguments.py", line 15, in <module>
    from utils.color.TextColor import paint
  File "C:\Users\info\Downloads\MCPTool-3.5\MCPTool-3.5\utils\color\TextColor.py", line 3, in <module>
    from colorama import Fore, init
ModuleNotFoundError: No module named 'colorama'

**Comment by vofq** [comment]
nevermind i foind out how to fix it, I did pip install colorama
ill be closing this now
