### ISSUE TITLE
Error (Español)

### ISSUE THREAD

**Issue by 1XFrankX1** [wrrulos/MCPTool#40]
Hola master, esta muy buena la tool pero el fakeproxy no anda ya que dice: 

Traceback (most recent call last):
  File "C:\Users\XXXXX\Desktop\MCPTool-main\main.py", line 179, in <module>
    menu()
  File "C:\Users\XXXXX\Desktop\MCPTool-main\main.py", line 114, in menu
    commands[command](*arguments[1:])
  File "C:\Users\XXXXX\Desktop\MCPTool-main\utils\commands\FakeProxy.py", line 14, in fakeproxy_command
    start_velocity(server, mode, fakeproxy=True)
  File "C:\Users\XXXXX\Desktop\MCPTool-main\utils\velocity\StartVelocity.py", line 169, in start_velocity
    WriteFile(f'utils/velocity/{location}/plugins/RPoisoner/settings/onlinePlayers', True, 'w+', data[3])
  File "C:\Users\XXXXX\Desktop\MCPTool-main\utils\writefile\WriteFile.py", line 18, in WriteFile
    with open(file, mode=mode, encoding='utf8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'utils/velocity/fakeproxy/plugins/RPoisoner/settings/onlinePlayers'

Que hago?

**Comment by wrrulos** [comment]
¿Puedes mandarme el comando que estás ejecutando exactamente?

**Comment by 1XFrankX1** [comment]
Pasa con todos de la ultima (none,modern,etc), EL que ejecute fue fakeproxy volatik.net none

**Comment by 1XFrankX1** [comment]
Peo pasa con otros servers tmb

**Comment by wrrulos** [comment]
Creo que ya encontré el error. Velocity necesita una de las versiones de java superiores para ejecutar el comando. Instala Java 17 (por ejemplo) y vuelve a ejecutar el comando..

**Comment by 1XFrankX1** [comment]
Dale ahora veo, grax

**Comment by wrrulos** [comment]
¡Dale! Mientras veré una manera para que la herramienta avisé que no tenes una versión de java superior.

**Comment by 1XFrankX1** [comment]
La sacaste rapido jaja, ahora si anda. !Gracias¡
