### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fluorek** [wrrulos/MCPTool#41]
Traceback (most recent call last):
  File "D:\pobane\MCPTool-main\main.py", line 11, in <module>
    from utils.commands.Aternos import aternos_command
  File "D:\pobane\MCPTool-main\utils\commands\Aternos.py", line 9, in <module>
    from utils.gets.IPAndPort import get_ip_port
  File "D:\pobane\MCPTool-main\utils\gets\IPAndPort.py", line 1, in <module>
    from utils.minecraft.ServerData import mcsrvstatus
  File "D:\pobane\MCPTool-main\utils\minecraft\ServerData.py", line 8, in <module>
    from mcstatus import JavaServer
ImportError: cannot import name 'JavaServer' from 'mcstatus' (C:\Users\wojti\AppData\Local\Programs\Python\Python39\lib\site-packages\mcstatus\__init__.py)

**Comment by wrrulos** [comment]
Reinstall mcstatus
