### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters

### ISSUE THREAD

**Issue by serentinos** [wrrulos/MCPTool#46]
```
$ python main.py

Traceback (most recent call last):
  File "C:\Users\stepa\Downloads\MCPTool\MCPTool-main\main.py", line 152, in <module>
    print_banner(f'pickaxe{settings["TYPE_OF_BANNERS"]}')
  File "C:\Users\stepa\Downloads\MCPTool\MCPTool-main\utils\banners\PrintBanner.py", line 28, in print_banner
    paint(banner)
  File "C:\Users\stepa\Downloads\MCPTool\MCPTool-main\utils\color\TextColor.py", line 23, in paint
    print(f'{text}{Fore.RESET}')
  File "C:\Users\stepa\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "C:\Users\stepa\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 177, in write
    self.write_and_convert(text)
  File "C:\Users\stepa\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 202, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\stepa\AppData\Local\Programs\Python\Python310\lib\site-packages\colorama\ansitowin32.py", line 210, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\stepa\AppData\Local\Programs\Python\Python310\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 62-69: character maps to <undefined>
```
Have this error. All npm and python packages are installed but something went wrong with encoding, could you help?

**Comment by wrrulos** [comment]
If it happens again, please reopen this post.
